In [3]:
import geopandas as gpd

In [4]:
gdf_h_merida = gpd.read_parquet("../data/processed/gdf_h_merida.parquet")
gdf_h_merida

,valid_time_utc,time_utc4,latitude,longitude,swvl1,swvl2,swvl3,stl1,sro,ssro,...,e,tp,evatc,evabs,evaow,evavt,geometry,index_right,NAME_1,NAME_2
346576,2020-01-01 00:00:00,2019-12-31 20:00:00,7.7,-71.5,0.324615,0.314331,0.354782,300.419678,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-71.5 7.7),170.0,Mérida,Padre Noguera
346595,2020-01-01 01:00:00,2019-12-31 21:00:00,7.7,-71.5,0.324570,0.314331,0.354782,299.561035,0.000000e+00,0.000003,...,-0.000009,0.000000e+00,-2.910383e-10,-0.000006,-2.174987e-06,0.000000e+00,POINT (-71.5 7.7),170.0,Mérida,Padre Noguera
346614,2020-01-01 02:00:00,2019-12-31 22:00:00,7.7,-71.5,0.324524,0.314346,0.354782,298.614746,0.000000e+00,0.000003,...,-0.000005,0.000000e+00,-2.910383e-10,-0.000004,-1.082895e-06,0.000000e+00,POINT (-71.5 7.7),170.0,Mérida,Padre Noguera
346633,2020-01-01 03:00:00,2019-12-31 23:00:00,7.7,-71.5,0.324509,0.314346,0.354782,297.727783,0.000000e+00,0.000003,...,-0.000003,2.607703e-08,-2.328306e-10,-0.000002,-7.377239e-07,1.164153e-10,POINT (-71.5 7.7),170.0,Mérida,Padre Noguera
346652,2020-01-01 04:00:00,2020-01-01 00:00:00,7.7,-71.5,0.324478,0.314362,0.354782,297.165771,7.450581e-09,0.000003,...,-0.000004,1.113862e-06,-3.492460e-10,-0.000002,-1.312932e-06,-1.164153e-10,POINT (-71.5 7.7),170.0,Mérida,Padre Noguera
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17409530,2026-03-31 19:00:00,2026-03-31 15:00:00,9.2,-70.9,0.430420,0.423981,0.427078,297.841064,1.745969e-04,0.000261,...,-0.000438,1.714796e-03,-3.315071e-04,-0.000082,-2.409378e-05,4.656613e-10,POINT (-70.9 9.2),165.0,Mérida,Julio César Salas
17409549,2026-03-31 20:00:00,2026-03-31 16:00:00,9.2,-70.9,0.431274,0.427460,0.427017,297.366455,5.111992e-04,0.000261,...,-0.000368,1.927555e-03,-2.879659e-04,-0.000063,-1.716753e-05,-4.656613e-10,POINT (-70.9 9.2),165.0,Mérida,Julio César Salas
17409568,2026-03-31 21:00:00,2026-03-31 17:00:00,9.2,-70.9,0.428894,0.429382,0.427063,296.620117,9.015203e-05,0.000284,...,-0.000250,9.267507e-04,-2.138205e-04,-0.000028,-8.374453e-06,0.000000e+00,POINT (-70.9 9.2),165.0,Mérida,Julio César Salas
17409587,2026-03-31 22:00:00,2026-03-31 18:00:00,9.2,-70.9,0.425934,0.428253,0.427689,295.645508,4.392862e-05,0.000261,...,-0.000175,5.008578e-04,-1.592906e-04,-0.000012,-3.953464e-06,0.000000e+00,POINT (-70.9 9.2),165.0,Mérida,Julio César Salas
17409606,2026-03-31 23:00:00,2026-03-31 19:00:00,9.2,-70.9,0.424103,0.427490,0.427704,295.035889,3.874302e-07,0.000261,...,-0.000051,5.811453e-06,-4.780944e-05,-0.000002,-1.219101e-06,0.000000e+00,POINT (-70.9 9.2),165.0,Mérida,Julio César Salas

In [5]:
gdf_h_merida.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 5805408 entries, 346576 to 17409606
Data columns (total 31 columns):
 #   Column          Dtype
---  ------          -----
 0   valid_time_utc  datetime64[ns]
 1   time_utc4       datetime64[ns]
 2   latitude        float64
 3   longitude       float64
 4   swvl1           float32
 5   swvl2           float32
 6   swvl3           float32
 7   stl1            float32
 8   sro             float32
 9   ssro            float32
 10  lai_lv          float32
 11  lai_hv          float32
 12  sp              float32
 13  sshf            float32
 14  slhf            float32
 15  u10             float32
 16  v10             float32
 17  t2m             float32
 18  d2m             float32
 19  ssrd            float32
 20  strd            float32
 21  e               float32
 22  tp              float32
 23  evatc           float32
 24  evabs           float32
 25  evaow           float32
 26  evavt           float32
 27  geometry        geometry
 28  index_right     float64
 29  NAME_1          str
 30  NAME_2          str
dtypes: datetime64[ns](2), float32(23), float64(3), geometry(1), str(2)
memory usage: 1020.4 MB

In [8]:
gdf_h_merida["mes"] = gdf_h_merida["time_utc4"].dt.month

In [21]:
print(gdf_h_merida.describe())

                      valid_time_utc                      time_utc4  \
count                        5805408                        5805408
mean   2023-02-14 23:30:00.000012544  2023-02-14 19:30:00.000017152
min              2020-01-01 00:00:00            2019-12-31 20:00:00
25%              2021-07-24 11:45:00            2021-07-24 07:45:00
50%              2023-02-14 23:30:00            2023-02-14 19:30:00
75%              2024-09-07 11:15:00            2024-09-07 07:15:00
max              2026-03-31 23:00:00            2026-03-31 19:00:00
std                              NaN                            NaN

           latitude     longitude         swvl1         swvl2         swvl3  \
count  5.805408e+06  5.805408e+06  5.805408e+06  5.805408e+06  5.805408e+06
mean   8.529245e+00 -7.124151e+01  3.874699e-01  3.883305e-01  3.871319e-01
min    7.700000e+00 -7.190000e+01  7.560730e-02  1.484070e-01  1.605377e-01
25%    8.300000e+00 -7.150000e+01  3.587952e-01  3.570099e-01  3.511200e-01
50%    8.500000e+00 -7.120000e+01  4.025421e-01  4.030914e-01  3.978729e-01
75%    8.800000e+00 -7.100000e+01  4.250031e-01  4.260559e-01  4.258575e-01
max    9.200000e+00 -7.060000e+01  5.200043e-01  5.200043e-01  5.200043e-01
std    3.455832e-01  3.015269e-01  6.703340e-02  6.559607e-02  6.317245e-02

               stl1           sro          ssro  ...         evatc  \
count  5.805408e+06  5.805302e+06  5.805302e+06  ...  5.805302e+06
mean   2.915358e+02  5.831154e-05  1.206494e-04  ... -4.967343e-05
min    2.754805e+02  0.000000e+00  1.490116e-08  ... -8.629640e-04
25%    2.883767e+02  1.713634e-07  2.466515e-05  ... -5.822256e-05
50%    2.913838e+02  3.173947e-06  7.253885e-05  ... -7.092953e-06
75%    2.945920e+02  2.264977e-05  1.541600e-04  ... -2.049637e-07
max    3.119082e+02  3.453669e-02  1.038246e-02  ...  2.684509e-04
std    4.305548e+00  2.874323e-04  1.900006e-04  ...  8.739596e-05

              evabs         evaow         evavt   index_right           mes  \
count  5.805302e+06  5.805302e+06  5.805302e+06  5.805408e+06  5.805408e+06
mean  -5.544505e-05 -2.500872e-05 -8.807948e-07  1.650377e+02  6.344216e+00
min   -7.056119e-04 -5.820990e-04 -2.159602e-04  1.560000e+02  1.000000e+00
25%   -6.810063e-05 -2.366537e-05 -1.676381e-07  1.600000e+02  3.000000e+00
50%   -1.876731e-06 -2.640299e-06  0.000000e+00  1.640000e+02  6.000000e+00
75%   -6.868504e-08 -9.406358e-08  0.000000e+00  1.690000e+02  9.000000e+00
max    9.313226e-10  3.029052e-04  1.007691e-05  1.770000e+02  1.200000e+01
std    9.865837e-05  5.264702e-05  6.057454e-06  6.053106e+00  3.497096e+00

         hora_local        tp_mmh         t2m_c       sro_mmh
count  5.805408e+06  5.805302e+06  5.805408e+06  5.805302e+06
mean   1.150000e+01  3.098226e-01  1.692990e+01  5.831154e-02
min    0.000000e+00  0.000000e+00  8.080139e-01  0.000000e+00
25%    5.750000e+00  3.129244e-03  1.314615e+01  1.713634e-04
50%    1.150000e+01  5.228817e-02  1.655704e+01  3.173947e-03
75%    1.725000e+01  2.904683e-01  2.058365e+01  2.264977e-02
max    2.300000e+01  4.012145e+01  3.802823e+01  3.453669e+01
std    6.922187e+00  6.900651e-01  5.086495e+00  2.874323e-01

[8 rows x 33 columns]

In [9]:
gdf_h_merida

,valid_time_utc,time_utc4,latitude,longitude,swvl1,swvl2,swvl3,stl1,sro,ssro,...,tp,evatc,evabs,evaow,evavt,geometry,index_right,NAME_1,NAME_2,mes
346576,2020-01-01 00:00:00,2019-12-31 20:00:00,7.7,-71.5,0.324615,0.314331,0.354782,300.419678,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,POINT (-71.5 7.7),170.0,Mérida,Padre Noguera,12
346595,2020-01-01 01:00:00,2019-12-31 21:00:00,7.7,-71.5,0.324570,0.314331,0.354782,299.561035,0.000000e+00,0.000003,...,0.000000e+00,-2.910383e-10,-0.000006,-2.174987e-06,0.000000e+00,POINT (-71.5 7.7),170.0,Mérida,Padre Noguera,12
346614,2020-01-01 02:00:00,2019-12-31 22:00:00,7.7,-71.5,0.324524,0.314346,0.354782,298.614746,0.000000e+00,0.000003,...,0.000000e+00,-2.910383e-10,-0.000004,-1.082895e-06,0.000000e+00,POINT (-71.5 7.7),170.0,Mérida,Padre Noguera,12
346633,2020-01-01 03:00:00,2019-12-31 23:00:00,7.7,-71.5,0.324509,0.314346,0.354782,297.727783,0.000000e+00,0.000003,...,2.607703e-08,-2.328306e-10,-0.000002,-7.377239e-07,1.164153e-10,POINT (-71.5 7.7),170.0,Mérida,Padre Noguera,12
346652,2020-01-01 04:00:00,2020-01-01 00:00:00,7.7,-71.5,0.324478,0.314362,0.354782,297.165771,7.450581e-09,0.000003,...,1.113862e-06,-3.492460e-10,-0.000002,-1.312932e-06,-1.164153e-10,POINT (-71.5 7.7),170.0,Mérida,Padre Noguera,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17409530,2026-03-31 19:00:00,2026-03-31 15:00:00,9.2,-70.9,0.430420,0.423981,0.427078,297.841064,1.745969e-04,0.000261,...,1.714796e-03,-3.315071e-04,-0.000082,-2.409378e-05,4.656613e-10,POINT (-70.9 9.2),165.0,Mérida,Julio César Salas,3
17409549,2026-03-31 20:00:00,2026-03-31 16:00:00,9.2,-70.9,0.431274,0.427460,0.427017,297.366455,5.111992e-04,0.000261,...,1.927555e-03,-2.879659e-04,-0.000063,-1.716753e-05,-4.656613e-10,POINT (-70.9 9.2),165.0,Mérida,Julio César Salas,3
17409568,2026-03-31 21:00:00,2026-03-31 17:00:00,9.2,-70.9,0.428894,0.429382,0.427063,296.620117,9.015203e-05,0.000284,...,9.267507e-04,-2.138205e-04,-0.000028,-8.374453e-06,0.000000e+00,POINT (-70.9 9.2),165.0,Mérida,Julio César Salas,3
17409587,2026-03-31 22:00:00,2026-03-31 18:00:00,9.2,-70.9,0.425934,0.428253,0.427689,295.645508,4.392862e-05,0.000261,...,5.008578e-04,-1.592906e-04,-0.000012,-3.953464e-06,0.000000e+00,POINT (-70.9 9.2),165.0,Mérida,Julio César Salas,3
17409606,2026-03-31 23:00:00,2026-03-31 19:00:00,9.2,-70.9,0.424103,0.427490,0.427704,295.035889,3.874302e-07,0.000261,...,5.811453e-06,-4.780944e-05,-0.000002,-1.219101e-06,0.000000e+00,POINT (-70.9 9.2),165.0,Mérida,Julio César Salas,3

In [10]:
gdf_h_merida["hora_local"] = gdf_h_merida["time_utc4"].dt.hour
gdf_h_merida["tp_mmh"] = gdf_h_merida["tp"] * 1000
gdf_h_merida["t2m_c"] = gdf_h_merida["t2m"] - 273.15
gdf_h_merida["sro_mmh"] = gdf_h_merida["sro"] * 1000

In [27]:
unique_points = gdf_h_merida[['latitude', 'longitude']].drop_duplicates()
n_points = len(unique_points)

106